### ISSUE TITLE
Clipboard not working [menu bar]

### ISSUE THREAD

**Issue by santi6291** [Alxmerino/Project-Timer#43]
Can't paste from clipboard in Menu bar app. This may help [Electron - Enable copy and paste](https://pracucci.com/atom-electron-enable-copy-and-paste.html)

**Comment by Alxmerino** [comment]
I noticed that, thanks for the link. Noted and will be added on the next release unless you want to tackle it

**Comment by Alxmerino** [comment]
This was resolved with the latest release `v1.3.1`
