### ISSUE TITLE
Multiple timers can run.

### ISSUE THREAD

**Issue by Alxmerino** [Alxmerino/Project-Timer#7]
When you start a timer, you're able to start another timer. When pausing one all timers remove the active state.

Should multiple timers be able to run at once or just one at a time?

**Comment by jkustra92** [comment]
i’m thinking, to answer your question, you should be able to have multiple timers running at once bc that would allow it to be more multi-purpose.

also i'm totally interested in tackling this issue and will let you know how it goes!

**Comment by Alxmerino** [comment]
@jkustra92 Fixed with #16
