### ISSUE TITLE
Run on hosted web space?  Not able to load/run yarn.

### ISSUE THREAD

**Issue by caryboe** [Alxmerino/Project-Timer#75]
This app is exactly what I'm looking for - great layout, thank you!  Looking to run on a hosted web platform. I'm not able to load/run yarn - any suggestions or advice would be greatly appreciated!  Thanks

**Comment by Alxmerino** [comment]
Thank you! you can always download a stand-alone version here https://github.com/Alxmerino/Project-Timer/releases/tag/v1.3.2

**Comment by caryboe** [comment]
Thank you for this information.  I appreciate your quick reply, but I'm
still not able to make it work.  The source code seems identical to my
previous download.  Is there something I'm missing?  The below screenshot
is what I have.

[image: image.png]

Thanks again, Carrie

**Comment by Alxmerino** [comment]
I'm unable to see your screenshot, you can download the app zipped here https://github.com/Alxmerino/Project-Timer/releases/download/v1.3.2/Project.Timer.zip

**Comment by caryboe** [comment]
Does this work?

Thanks again for your help, you're awesome!

**Comment by caryboe** [comment]
With the link I was provided in the previous message, I downloaded the files but it seems like these are the same files as the non stand-alone version.  Below is a paste of the html file in that stand-alone download.  I am not able to build this with npm and/or yarn as I am trying to upload and use this on a hosted platform for which I do not have access to installing and/or running npm or yarn.  Please help.  

      **This HTML file is a template.
      If you open it directly in the browser, you will see an empty page.

      You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the <body> tag.

      To begin the development, run `npm start` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.**

**Comment by caryboe** [comment]
Got this to work on my rhel 8 box, but I cannot use it anywhere else other than on that box.  This is a great app, but to me, it seems so unnecessarily complicated to use and setup.  I'd like to simply use it one some web space, but you need to use npm or yarn to make this work - and I cannot figure out how to export it to use it elsewhere.  I was hoping to not write my own code, but I think I just may have to - thanks anyway.

**Comment by Alxmerino** [comment]
I'm glad you got it to work, this is an old setup so yes, it is a bit complicated. In the future when I have more time I'm planning to re-write it from scratch.
